version: '3.9'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root1234
    command: [ "--auth" ]
    volumes:
      - mongo-data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: springboot-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://skeleton_user:qlqjs1212@localhost:27017/skeleton
    depends_on:
      - mongo

volumes:
  mongo-data:

