version: '3.9'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: init
      MONGO_INITDB_ROOT_PASSWORD: initpw
    command: [ "--auth" ]
    volumes:
      - mongo-data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
  mongo-data: